- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
- name: Ensure group "prometheus" exists
  group:
    name: prometheus
    state: present
- name: Add the user 'prometheus' to group 'prometheus'
  user:
    name: prometheus
    comment: prometheus
    group: prometheus 
- name: Creates directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
- name: Creates directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus
