- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
- name: Ensure group "prometheus" exists
  group:
    name: prometheus
    state: present
